navig/navig/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.db.models.aggregates import Count
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.contrib.auth.views import password_reset_confirm
from oxero.models import ExampleItinerary
from oxero.views import (
    StaticPageView, SiteView, SiteDetailVeiw, ItineraryDetailVeiw,
    SetLanguageView, SearchView, ExploreView
)
from accounts.views import (
    RegistrationView, RegistrationConfirmView, LoginView, ResetPasswordView,
    LogoutView
)
from oxero.views import personalize

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^set_language/', SetLanguageView.as_view(), name='set_language'),
    url(r'^comments/', include('django.contrib.comments.urls')),
)

urlpatterns += i18n_patterns('',
    url(r'^$', ListView.as_view(
            template_name="index.html",
            queryset=ExampleItinerary.objects.annotate(
                num_days=Count('exampleitinerarysite')
            ),
            context_object_name='example_itineraries'
        ),
        name="home"
    ),
    url(r'^aboutus$',
        StaticPageView.as_view(template_name="aboutus"), name="aboutus"
    ),
    url(r'^advertising$',
        StaticPageView.as_view(template_name="advertising"), name="advertising"
    ),
    url(r'^contactus$',
        StaticPageView.as_view(template_name="contactus"), name="contactus"
    ),
    url(r'^explore$', ExploreView.as_view(), name="explore"),
    url(r'^info$',
        StaticPageView.as_view(template_name="info"), name="info"
    ),
    url(r'^itinerarydetails/(?P<pk>\d+)$',
        ItineraryDetailVeiw.as_view(), name="itinerarydetails"
    ),
    url(r'^itineraryexamples$', ListView.as_view(
            template_name="itineraryexamples.html",
            queryset=ExampleItinerary.objects.annotate(
                num_days=Count('exampleitinerarysite')
            ),
            context_object_name='example_itineraries'
        ),
        name="itineraryexamples"
    ),
    url(r'^legal$',
        StaticPageView.as_view(template_name="legal"), name="legal"
    ),
    url(r'^printpreview/(?P<pk>\d+)$',
        personalize.PrintPreview.as_view(),
        name="printpreview"
    ),
    url(r'^sitedetails/(?P<pk>\d+)$',
        SiteDetailVeiw.as_view(), name='sitedetails'
    ),
    url(r'^sites$', SiteView.as_view(), name="sites"),
    url(r'^registration$', RegistrationView.as_view(), name="registration"),
    url(r'^confirm_registration/(?P<id>\w+)/(?P<confirmation_hash>\w+)$',
        RegistrationConfirmView.as_view(), name="confirmregistration"
    ),
    url(r'^login$', LoginView.as_view(), name="login"),
    url(r'^logout$', LogoutView.as_view(), name="logout"),
    url(r'^reset_password$',
        ResetPasswordView.as_view(), name="resetpassword"
    ),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm, {
            'template_name': 'password_reset_confirm.html',
            'post_reset_redirect': '/'
        },
        name='passwordresetconfirm'
    ),
    # Personalize urls
    url(r'^personalize$', personalize.ItineraryView.as_view(), name='personalize'),
    url(r'^personalize/itinerary$', personalize.ItineraryView.as_view()),
    url(r'^personalize/itinerary/(?P<id>\d+)$', personalize.ItineraryView.as_view(), name='viewcustomitinerary'),
    url(r'^personalize/itinerary/recommendation$', personalize.RecommendationView.as_view()),
    url(r'^personalize/itinerary_place/(?P<itinerary_id>\d+)$', personalize.ItineraryPlaceView.as_view()),
    url(r'^personalize/itinerary_place/(?P<itinerary_id>\d+)/site/(?P<site_id>\d+)$', personalize.ItineraryPlaceView.as_view()),
    url(r'^personalize/itinerary_place_activity/(?P<id>\d+)$', personalize.ItineraryPlaceActivityView.as_view()),
    url(r'^personalize/itinerary_place_activity/(?P<itinerary_id>\d+)-(?P<site_id>\d+)-(?P<activity_id>\d+)$', personalize.ItineraryPlaceActivityView.as_view()),
    url(r'^personalize/itinerary_place_hoteal$', personalize.ItineraryPlaceHotelView.as_view()),
    url(r'^personalize/itinerary_place_hoteal/(?P<id>\d+)$', personalize.ItineraryPlaceHotelView.as_view()),
    # Search
    url(r'^search$',
        SearchView.as_view(), name="search"
    ),
)

navig/navig/models.py
from itertools import product
from django.contrib.auth.models import User
from django.db import models

from django.utils.translation import ugettext as _
from transmeta import TransMeta
from stdimage.fields import StdImageField


class ActiveManager(models.Manager):
    """
    Manager class that returns active records
    """
    def get_query_set(self):
        return super(ActiveManager, self).get_query_set().filter(is_active=True)


class CommonMixin(models.Model):
    """
    Abstract base class for common information
    """
    is_active       = models.BooleanField(default=True)
    last_active     = models.DateField(auto_now=True)
    date            = models.DateField(auto_now_add=True)

    objects     = models.Manager()
    active      = ActiveManager()

    class Meta:
        abstract = True


class ImageMixin(models.Model):
    width = models.IntegerField(blank=True, null=True, editable=False)
    height = models.IntegerField(blank=True, null=True, editable=False)

    def save(self, *args, **kwargs):
        try:
            this = ImageMixin.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete(save=False)
        except: pass # when new photo then we do nothing, normal case
        super(ImageMixin, self).save(args, kwargs)

    def delete(self, using=None):
        super(ImageMixin, self).delete(using)
        self.image.delete(save=False)

    class Meta:
        abstract = True


class StaticPage(models.Model):
    __metaclass__ = TransMeta

    name = models.CharField(max_length=255, verbose_name=_("Name"))
    content = models.TextField(verbose_name=_("Name"))

    def __unicode__(self):
        return self.name

    class Meta:
        translate = ('content',)


class Site(CommonMixin, ImageMixin):
    __metaclass__ = TransMeta

    name = models.CharField(max_length=255, verbose_name=_("Name"))
    description = models.TextField(verbose_name=_("Description"))
    has_airport = models.BooleanField(default=False)
    rating = models.IntegerField()
    order = models.IntegerField()
    do_not_miss = models.TextField(verbose_name=_("Do not miss"))
    recommended_stay = models.TextField(verbose_name=_("Recommended stay"))
    address = models.CharField(max_length=255, verbose_name=_("Address"))
    state = models.CharField(max_length=100, verbose_name=_("State"))
    price = models.TextField(verbose_name=_("Price"))
    good_to_know = models.TextField(verbose_name=_("Good to know"))
    link = models.URLField(blank=True, null=True)
    region = models.ManyToManyField('Region', blank=True, null=True)
    interests = models.ManyToManyField('Interest', blank=True, null=True)
    map = StdImageField(
        upload_to='uploaded_images/%Y/%m/%d',
        max_length=255,
        height_field='height',
        width_field='width',
        size=(453, 294, True),
        thumbnail_size=(195, 150, True),
        blank=True,
        null=True
    )
    location_lat = models.DecimalField(
        u'Location (latitude)', max_digits=10, decimal_places=7, default=0,
        help_text=u"You can use http://www.getlatlon.com to get a location's coordinates"
    )
    location_lon = models.DecimalField(
        u'Location (longitude)', max_digits=10, decimal_places=7, default=0,
        help_text=u"You can use http://www.getlatlon.com to get a location's coordinates"
    )


    def get_next(self):
        next = Site.objects.filter(id__gt=self.id)
        if next:
          return next[0]
        return False


    def get_prev(self):
        prev = Site.objects.filter(id__lt=self.id)
        if prev:
          return prev[0]
        return False


    def __unicode__(self):
        return self.name


    @models.permalink
    def get_url(self):
        return ('sitedetails', (), { 'pk': self.id })


    class Meta:
        translate = (
            'description',
            'do_not_miss',
            'recommended_stay',
            'address',
            'state',
            'price',
            'good_to_know',
        )


class SiteImage(CommonMixin, ImageMixin):
    site = models.ForeignKey('Site')
    image = StdImageField(
        upload_to='uploaded_images/%Y/%m/%d',
        max_length=255,
        height_field='height',
        width_field='width',
        size=(246, 160, True),
        thumbnail_size=(200, 148, True),
        blank=True,
        null=True
    )

    def __unicode__(self):
        return u"%s image" % self.site.name


class SiteActivity(CommonMixin, ImageMixin):
    __metaclass__ = TransMeta


    site = models.ForeignKey('Site')
    name = models.CharField(max_length=255, verbose_name=_("Name"))
    description = models.TextField(verbose_name=_("Description"))
    price = models.CharField(max_length=100)
    image = StdImageField(
        upload_to='uploaded_images/%Y/%m/%d',
        max_length=255,
        height_field='height',
        width_field='width',
        size=(183, 112, True),
        blank=True,
        null=True
    )

    def __unicode__(self):
        return self.name

    class Meta:
        translate = ('name', 'description')


class SiteActivityImage(CommonMixin, ImageMixin):
    site_activity = models.ForeignKey('SiteActivity')
    image = StdImageField(
        upload_to='uploaded_images/%Y/%m/%d',
        max_length=255,
        height_field='height',
        width_field='width',
        size=(266, 175, True),
        blank=True,
        null=True
    )

    def __unicode__(self):
        return u"%s image" % self.site_activity.name


class SiteHotel(CommonMixin):
    __metaclass__ = TransMeta

    name = models.CharField(max_length=255, verbose_name=_("Name"))
    description = models.TextField(verbose_name=_("Description"))
    price = models.FloatField()

    def __unicode__(self):
        return self.name

    class Meta:
        translate = ('name', 'description')


#class SiteCar(CommonMixin):
#    __metaclass__ = TransMeta
#
#    name = models.CharField(max_length=255)
#    description = models.TextField()
#
#    class Meta:
#        translate = ('name', 'description')


class Itinerary(CommonMixin):
    __metaclass__ = TransMeta

    user = models.ForeignKey(User, blank=True, null=True)
    session_key = models.CharField(max_length=50, blank=True, null=True)
    name = models.CharField(max_length=255, verbose_name=_("Name"))
    description = models.TextField(verbose_name=_("Description"), blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    sites = models.ManyToManyField('Site', through='ItinerarySite')

    def __unicode__(self):
        return self.name

    class Meta:
        translate = ('name', 'description')


class ItinerarySite(CommonMixin):
    # @todo: find out if car field should be added
    itinerary = models.ForeignKey('Itinerary')
    site = models.ForeignKey('Site')
    nights = models.IntegerField()
    order = models.IntegerField()
    start_date = models.DateField(blank=True, null=True)
    # @todo: you can book multiple hotels
    # hotel = models.ForeignKey('SiteHotel', blank=True, null=True)
    activities = models.ManyToManyField('SiteActivity', through='ItineraryPlaceActivity')

    def __unicode__(self):
        return u"%s - %s" % (self.itinerary.name, self.site.name)

    class Meta:
        ordering = ['order']


class ItineraryPlaceActivity(CommonMixin):
    site = models.ForeignKey('ItinerarySite')
    activity = models.ForeignKey('SiteActivity')
    is_booked = models.BooleanField(default=False)

    def __unicode__(self):
        return u"%s - %s - %s" % (self.site.itinerary.name, self.site.site.name, self.activity.name)


class Region(CommonMixin):
    name = models.CharField(max_length='255')

    def __unicode__(self):
        return self.name


class Interest(CommonMixin):
    __metaclass__ = TransMeta

    name = models.CharField(max_length='255', verbose_name=_("Name"))

    def __unicode__(self):
        return self.name

    class Meta:
        translate = ('name',)


class SiteComment(CommonMixin):
    user = models.ForeignKey(User)
    site = models.ForeignKey(Site)
    comment = models.TextField(verbose_name=_("Leave a comment"))

    def __unicode__(self):
        return 'Comment by %s' % self.user.username


class ExampleItinerary(CommonMixin, ImageMixin):
    __metaclass__ = TransMeta

    name = models.CharField(max_length=255, verbose_name=_("Name"))
    description = models.TextField(verbose_name=_("Description"), blank=True, null=True)
    map = StdImageField(
        upload_to='uploaded_images/%Y/%m/%d',
        max_length=255,
        height_field='height',
        width_field='width',
        size=(472, 306, True),
        thumbnail_size=(273, 150, True),
        blank=True,
        null=True
    )

    def get_next(self):
        next = Itinerary.objects.filter(id__gt=self.id)
        if next:
          return next[0]
        return False

    def get_prev(self):
        prev = Itinerary.objects.filter(id__lt=self.id)
        if prev:
          return prev[0]
        return False

    class Meta:
        translate = ('name', 'description')


class ExampleItineraryImage(CommonMixin, ImageMixin):
    example_itinerary = models.ForeignKey('ExampleItinerary')
    image = StdImageField(
        upload_to='uploaded_images/%Y/%m/%d',
        max_length=255,
        height_field='height',
        width_field='width',
        size=(246, 160, True),
        blank=True,
        null=True
    )

    def __unicode__(self):
        return u"%s image" % self.example_itinerary.name


class ExampleItinerarySite(CommonMixin):
    example_itinerary = models.ForeignKey('ExampleItinerary')
    day_number = models.IntegerField()
    from_site = models.ForeignKey('Site', related_name='+')
    to_site = models.ForeignKey('Site', related_name='+')


class ExampleItinerarySiteDetail(models.Model):
    example_itinerary_site = models.ForeignKey('ExampleItinerarySite')
    description = models.CharField(max_length=255)

navig/navig/templates/explore.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<div class="row-fluid">
		<div class="span12 subnav">
			<ul class="unstyled">
				<li><a href="{% url explore %}" class="active">{% trans "Overview" %}</a></li>
				<li>|</li>
				<li><a href="{% url itineraryexamples %}">{% trans "Itinerary Examples" %}</a></li>
				<li>|</li>
				<li><a href="{% url sites %}">{% trans "Sites" %}</a></li>
			</ul>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<h2>{% trans "MAP OVERVIEW" %}</h2>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="mapWrapper">
				<!--<img style="-webkit-user-select: none" src="http://maps.googleapis.com/maps/api/staticmap?center=Grand+Canyon+AZ&amp;zoom=5&amp;size=600x300&amp;maptype=roadmap&amp;sensor=false" alt="{% trans 'Map Overview' %}">-->
				<div id="mapOverview" style="width:100%; height:300px;"></div>
			</div>
		</div>
	</div>
{% endblock content %}

{% block extraJS %}
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}&sensor=false"></script>
	<script type="text/javascript">
		(function()
		{
			var mapOptions =
			{
				center: new google.maps.LatLng(35, -117),
				zoom: 5,
				mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			var mapOverview = new google.maps.Map(document.getElementById("mapOverview"), mapOptions);
			{% for currentSite in allSites %}
	 			var newMarker = new google.maps.Marker(
	 			{
	 				map: mapOverview,
	 				position: new google.maps.LatLng({{ currentSite.location_lat }}, {{ currentSite.location_lon }}),
	 				title: '{{ currentSite.name }}. Click to see more details.'
	 			});
				google.maps.event.addListener(newMarker, 'click', function()
				{
					window.location = '{{ currentSite.get_url }}';
				});
			{% endfor %}
		})();
	</script>
{% endblock extraJS %}

navig/navig/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<div class="row-fluid pyrt">
		<div class="span12"><h2 class="center colororange">
			{% trans "PLAN YOUR ROAD-TRIP HOLIDAYS IN A FEW CLICKS AT NO COST" %}
		</h2></div>
		<div class="row-fluid">
			<div class="span5">
				<div class="carousel-wrapper">
					<div id="homeCarousel" class="carousel slide">
						<!-- Carousel items -->
						<div class="carousel-inner">
							<div class="active item">
								<a href="images/sampleimage.jpg">
								<img src="{{ STATIC_URL }}images/sampleimage.jpg" alt="{% trans 'Sample image' %}"/>
								<!--
								<div class="carousel-caption">
									<h4>This is a caption</h4>
									<p>And a paragraph description of the image.</p>
								</div>
								-->
								</a>
							</div>
							<div class="item"><a href="images/sampleimageB.jpg"><img src="{{ STATIC_URL }}images/sampleimageB.jpg" alt="{% trans 'Sample image' %}"/></a></div>
							<div class="item"><a href="images/sampleimageC.jpg"><img src="{{ STATIC_URL }}images/sampleimageC.jpg" alt="{% trans 'Sample image' %}"/></a></div>
						</div>
						<!-- Carousel nav -->
						<a class="carousel-control left" href="#homeCarousel" data-slide="prev">&lsaquo;</a>
						<a class="carousel-control right" href="#homeCarousel" data-slide="next">&rsaquo;</a>
					</div>
				</div>
			</div>
			<div class="span7 tools">
				<h3 class="center black">{% trans "All the tools you need to plan your dream itinerary." %}</h3>
				<div class="row-fluid">
					<div class="span4">
						<a href="{% url itineraryexamples %}" class="dreamItinerary">
						<div>
							<img src="{{ STATIC_URL }}images/sampleimage.jpg" alt="{% trans 'Sample image' %}"/>
						</div>
						<h3 class="center">{% trans "See itinerary examples" %}</h3>
						</a>
					</div>
					<div class="span4">
						<a href="{% url sites %}" class="dreamItinerary">
						<div>
							<img src="{{ STATIC_URL }}images/sampleimage.jpg" alt="{% trans 'Sample image' %}"/>
						</div>
						<h3 class="center">{% trans "Get informations on site to visit" %}</h3>
						</a>
					</div>
					<div class="span4">
						<a href="{% url personalize %}" class="dreamItinerary">
						<div>
							<img src="{{ STATIC_URL }}images/sampleimage.jpg" alt="{% trans 'Sample image' %}"/>
						</div>
						<h3 class="center">{% trans "Design your trip" %}</h3>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12 howtohead"><h2 class="center">{% trans "HOW TO DESIGN YOU TRIP" %}</h2></div>
	</div>
	<div class="row-fluid howtobody">
		<div class="span12">
			<div class="span6">
				<div class="step"><img src="{{ STATIC_URL }}images/defineyourinterest.jpg" alt="{% trans 'Define your interest' %}"/></div>
				<div class="step"><img src="{{ STATIC_URL }}images/personalizeyouritenerary.jpg" alt="{% trans 'Personalize your itinerary' %}"/></div>
			</div>
			<div class="span6">
				<div class="step"><img src="{{ STATIC_URL }}images/addhotelsandactivities.jpg" alt="{% trans 'Add hotels and activities' %}"/></div>
				<div class="step"><img src="{{ STATIC_URL }}images/printyourtravelbooks.jpg" alt="{% trans 'Print your travel books' %}"/></div>
			</div>
		</div>
	</div>
	<div class="row-fluid howtobody">
		<div class="span12 marbot10">
			<a href="{% url personalize %}" class="btn btn-warning drop-center">{% trans "Design Your Trip Now" %}</a>
		</div>
	</div>
	{% if example_itineraries %}
		<div class="row-fluid recently-planned-header">
			<div class="span12">
				<h2 class="colororange">{% trans "EXAMPLE ITINERARIES" %}</h2>
			</div>
		</div>
		<div class="row-fluid recently-planned-body">
			<div class="span12 item-carousel">
				<ul id="itemcarousel" class="jcarousel-skin-tango unstyled">
					{% for example_itinerary in example_itineraries %}
						<li>
							<div class="itinerary item-holder">
								<a href="{% url itinerarydetails example_itinerary.pk %}">
									<div class="header">
										<h3>{{ example_itinerary.name }}</h3>
									</div>
									<div class="map">
										<img src="{{ STATIC_URL }}{{ example_itinerary.map.thumbnail.url }}" />
									</div>
									<h3>{{ example_itinerary.num_days|default_if_none:"0" }} Days</h3>
									<p>{{ example_itinerary.description }}</p>
								</a>
							</div>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	{% endif %}
{% endblock content %}

navig/navig/templates/itinerarydetails.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<div class="row-fluid">
		<div class="span12 subnav">
			<ul class="unstyled">
				<li><a href="{% url explore %}">{% trans "Overview" %}</a></li>
				<li>|</li>
				<li><a href="{% url itineraryexamples %}" class="active">{% trans "Itinerary Examples" %}</a></li>
				<li>|</li>
				<li><a href="{% url sites %}">{% trans "Sites" %}</a></li>
			</ul>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<a href="{% url itineraryexamples %}" class="back"></a>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span8">
			<div class="row-fluid mapDetail">
				<div class="row-fluid">
					<h2 class="center">1. {% trans "Best of California" %}</h2>
				</div>
				<div class="row-fluid">
					<div class="span1">
						{% if itinerary.get_prev %}
							<a href="{% url itinerarydetails itinerary.get_prev.pk %}" class="prevItemDetail"></a>
						{% endif %}
					</div>
					<div class="span10 map">
						<a href="#" class="lightbox">
							{% if itinerary.map %}
								<img src="{{ STATIC_URL }}{{ itinerary.map.url }}" />
							{% endif %}
						</a>
					</div>
					<div class="span1">
						{% if itinerary.get_next %}
							<a href="{% url itinerarydetails itinerary.get_next.pk %}" class="nextItemDetail"></a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
		<div class="span4 siteDetailPhotos">
			<h3 class="center black">{% trans "Photos" %}</h3>
			<div class="carousel-wrapper">
				<div id="detailCarousel" class="carousel slide detailCarousel">
					<!-- Carousel items -->
					<div class="carousel-inner">
						{% for image in itinerary.exampleitineraryimage_set.all %}
							<div class="{% if forloop.first %}active{% endif %} item">
								<a href="{{ STATIC_URL }}{{ image.image.url }}" >
									<img src="{{ STATIC_URL }}{{ image.image.url }}" alt="{% trans 0Southern California0 %}" />
								</a>
							</div>
						{% endfor %}
					</div>
					<!-- Carousel nav -->
					<a class="carousel-control left" href="#detailCarousel" data-slide="prev">&lsaquo;</a>
					<a class="carousel-control right" href="#detailCarousel" data-slide="next">&rsaquo;</a>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12 personalize">
			<a href="#" class="btn btn-warning drop-center">{% trans "Personalize This Itinerary" %}</a>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<h2 class="border-bottom">{% trans "Summary of Itinerary" %}</h2>
			<table class="table table-bordered table-striped itinerary-table">
				<tbody>
					{% for site in itinerary.exampleitinerarysite_set.all %}
						<tr>
							<td><strong class="colororange">{% trans "Day" %} {{ forloop.counter }}</strong></td>
							<td><strong>{{ site.from_site.name }} / {{ site.to_site.name }}</strong> - {{ site.exampleitinerarysitedetail_set.all.0.description }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<h2 class="border-bottom">{% trans "Explore the Map" %}</h2>
			<div class="bigMap"><img src="http://maps.googleapis.com/maps/api/staticmap?center=Grand+Canyon+AZ&zoom=6&size=450x200&scale=2&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Ccolor:red%7Clabel:C%7C40.718217,-73.998284&sensor=false"></div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12 container-fluid">
			<h2 class="border-bottom">{% trans "Details Day By Day" %}</h2>
			{% for site in itinerary.exampleitinerarysite_set.all %}
				<div class="row-fluid daybyday">
					<div class="span12">
						<div class="row-fluid">
							<div class="span12 marbot10">
								<h3 class="border-bottom">
									{% trans "Day" %} {{ forloop.counter }} - {{ site.from_site.name }} / {{ site.to_site.name }} - {{ site.exampleitinerarysitedetail_set.all.0.description }}
								</h3>
							</div>
						</div>
						<div class="row-fluid">
							{% for image in site.to_site.siteimage_set.all|slice:":1" %}
								<div class="span3"><img src="{{ STATIC_URL }}{{ image.image.thumbnail.url }}" alt="{% trans 'Depart' %}"/></div>
								{% empty %}
								<div class="span3"></div>
							{% endfor %}
							<div class="span9">
								<ul class="verticallist">
									{% for detail in site.exampleitinerarysitedetail_set.all %}
										<li>{{ detail.description }}</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{%endblock content%}

navig/navig/templates/itineraryexamples.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<div class="row-fluid">
		<div class="span12 subnav">
			<ul class="unstyled">
				<li><a href="{% url explore %}">{% trans "Overview" %}</a></li>
				<li>|</li>
				<li><a href="{% url itineraryexamples %}" class="active">{% trans "Itinerary Examples" %}</a></li>
				<li>|</li>
				<li><a href="{% url sites %}">{% trans "Sites" %}</a></li>
			</ul>
		</div>
	</div>
	<div class="row-fluid">
		<h1 class="page-title">{% trans "ITINERARY EXAMPLES" %}</h1>
	</div>
	{% if example_itineraries %}
		<div class="row-fluid">
			<div class="span12 marbot10">
				{% for example_itinerary in example_itineraries %}
					<div class="span4 itinerary">
						<a href="{% url itinerarydetails example_itinerary.pk %}">
							<div class="header">
								<h3>{{ example_itinerary.name }}</h3>
							</div>
							<div class="map">
								{% if example_itinerary.map %}
									<img src="{{ STATIC_URL }}{{ example_itinerary.map.thumbnail.url }}" />
								{% endif %}
							</div>
							<h3>{{ example_itinerary.num_days|default_if_none:"0" }} {% trans "Days" %}</h3>
							<p>{{ example_itinerary.description }}</p>
						</a>
					</div>
					{% if forloop.counter|divisibleby:"3" and not forloop.last %}
						</div>
						</div>
						<div class="row-fluid"><div class="span12 marbot10">
					{% endif %}
				{% endfor %}
			</div>
		</div>
	{% endif %}
{%endblock content%}

navig/navig/templates/static_page.html
{% extends "base.html" %}

{% block content %}
	{{ content|safe }}
{% endblock content %}